project_id: '448024'
api_token: >-
  433061d16c8b8068a43dd299cd3fcbde913459f188c0a1eee706bb562a29eb1b6ace7d402870a4c2
files:
  - source: /en/*
    ignore:
      - index
    translation: /%two_letters_code%/%original_file_name%
